deploy.tmpl.nomad
these changes aren't really necessary but i'm trying to get a new commit into master to see if that fixes the `git checkout` issue that i'm seeing on our build server.
=> changed resource allocations

contribs/build.gradle, contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java
support url encoded format in the http task request
=> #passing urlencode param in http task fixed

deploy.tmpl.nomad
* Fix hard-coded environment type.
=> dev -> master

docker/server/bin/startup.sh
* added wait to `docker/server/bin/startup.sh`
=> added 2 minute wait on server startup

common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java, common/src/main/java/com/netflix/conductor/common/run/Workflow.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java
=> Owcond 125

es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/Elasticsearch5Module.java
=> OWCOND-188 (Conductor ES disconnection case Test Scenario)

common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java, core/src/main/java/com/netflix/conductor/core/execution/ParametersUtils.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
=> OWCOND-189 (Get task/workflow status while publishing start/end nats message)

contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/NATSAbstractQueue.java, contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/NATSObservableQueue.java, contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/NATSStreamObservableQueue.java, es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/Elasticsearch5Module.java, server/src/main/java/com/netflix/conductor/log4j/KeyValueLayout.java
Reverts d3sw/conductor#118
We decided to include this piece next sprint. (sprint 4)
=> Revert "OWCOND-191 (Provide notify=true to logged message)"

contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/NATSStreamObservableQueue.java
=> Revert "OWCOND-102 - Nats event handler refactoring. Take the subject name fr…"

contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/NATSStreamObservableQueue.java
=> Revert "Revert "OWCOND-102 - Nats event handler refactoring. Take the subject name fr…""

common/src/main/java/com/netflix/conductor/common/run/Workflow.java, core/src/main/java/com/netflix/conductor/core/execution/ParametersUtils.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java
=> Revert "OWCOND-173 (Get Header info from Start Workflow)"

deploy.tmpl.nomad, docker/server/bin/startup.sh
=> OWCOND-224 - Vault Integration in Conductor

jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java
Added the header option in swagger ui for Deluxe-Owf-Context
=> Owcond 226 swaggerui

deploy.tmpl.nomad, docker/server/bin/startup.sh, server/src/main/java/com/netflix/conductor/server/Main.java
=> Revert "OWCOND-235 - Log information before app is killed."

core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
I've copied the code from the Netflix master branch
=> OWCOND-228 - Retry attempts on getemailspec & getnotificationspec

common/src/main/java/com/netflix/conductor/common/metadata/workflow/SubWorkflowParams.java, core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
=> Revert "OWCOND-254 - restart subworkflow"

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
have RUNNING Status instead of COMPLETED
=> OWCOND-310 - Conductor Nats event message Workflow Status

core/build.gradle, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
Starting these WF types responds with status 500
=> ONECOND-362 - Authorization Required Workflows

deploy.tmpl.nomad
=> Revert "Update deploy.tmpl.nomad"

client/build.gradle, contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/NATSAbstractQueue.java, core/build.gradle, core/src/main/java/com/netflix/conductor/core/events/EventProcessor.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, core/src/main/java/com/netflix/conductor/metrics/Monitors.java, deploy.tmpl.nomad, jersey/src/main/java/com/netflix/conductor/server/resources/InfoResource.java, jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java, server/src/main/java/com/netflix/conductor/server/ServerModule.java
+ spectator-api upgraded to 0.68.0 per Netflix latest code
=> ONECOND-355 - Data Dog Alert for Conductor

contribs/src/main/java/com/netflix/conductor/contribs/validation/ValidationTask.java
=> Revert "Overall reason fix for validation task-ONECOND-358"

core/src/main/java/com/netflix/conductor/core/execution/WorkflowSweeper.java, core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorkerCoordinator.java, deploy.tmpl.nomad
Added configs instead of hardcoded values.
=> ONECOND-444 - conductor db response time is long

deploy.tmpl.nomad
=> Revert "ONECOND-444 - conductor db response time is long"

deploy.tmpl.nomad
New Environment setup for conductor /workflow composer. Minor changes to avoid file overwriting
=> ONECOND-534 - Minor changes to avoid file overwriting

contribs/build.gradle, core/build.gradle, core/src/main/java/com/netflix/conductor/core/events/EventProcessor.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowSweeper.java, core/src/main/java/com/netflix/conductor/core/execution/tasks/Fail.java, core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorkerCoordinator.java, jersey/build.gradle, jersey/src/main/java/com/netflix/conductor/server/resources/TaskResource.java, jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java, server/src/main/java/com/netflix/conductor/log4j/KeyValueLayout.java
=> ONECOND-671 - Add more log for the reset workflow faileure

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, core/src/main/java/com/netflix/conductor/core/execution/batch/BatchSweeper.java, core/src/main/java/com/netflix/conductor/core/execution/tasks/Batch.java
=> ONECOND-668 - Batch Sherlock Task

deploy.tmpl.nomad
ONECOND-702 - Investigate the long delay between MSS and wf getting triggered
=> ONECOND-702 - Investigate the long delay between MSS and wf getting triggered

deploy.tmpl.nomad
ONECOND-668 - Batch Sherlock Task. Configuration
=> ONECOND-668 - Batch Sherlock Task. Configuration

deploy.tmpl.nomad
=> Update deploy.tmpl.nomad (Changing to weekly)

jersey/src/main/java/com/netflix/conductor/server/resources/InfoResource.java
Resolve naming issues so that the updated metrics should appear in Datadog.
=> Clean up /metrics endpoints

contribs/src/main/java/com/netflix/conductor/contribs/asset/AssetMonitor.java, core/src/main/java/com/netflix/conductor/core/events/FindUpdateAction.java, core/src/main/java/com/netflix/conductor/core/events/ScriptEvaluator.java, core/src/test/java/com/netflix/conductor/core/events/FindUpdateActionTest.java
=> ONECOND-784 SourceWait Workflow and Handler for the Sherlock Optimization

common/src/main/java/com/netflix/conductor/common/run/CommonParams.java, common/src/main/java/com/netflix/conductor/common/run/Workflow.java, contribs/src/main/java/com/netflix/conductor/contribs/http/GenericHttpTask.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, deploy.tmpl.nomad, jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java
=> Revert "Revert "Handling Auth context header -ONECOND-573""

.gitignore, common/src/main/java/com/netflix/conductor/common/run/Workflow.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, core/src/main/java/com/netflix/conductor/metrics/Monitors.java, jersey/src/main/java/com/netflix/conductor/server/resources/InfoResource.java
Updates to the `/v1/metrics` endpoint to support a Datadog dashboard.
=> Add more metrics

contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java, contribs/src/main/java/com/netflix/conductor/contribs/http/HttpWaitTask.java
=> Revert "Prevent URI Corruption"

contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java, contribs/src/main/java/com/netflix/conductor/contribs/http/HttpWaitTask.java
Reapply the earlier changes for 837 along with the fixes made this morning.
=> Reapply ONECOND-837

core/src/main/java/com/netflix/conductor/core/execution/batch/SherlockBatchProcessor.java
Batch extension to support endpoint per task definition and grouped by that task
=> ONECOND-855 - Update V2 SourceWait conductor flow

deploy.tmpl.nomad
Improve service availability during deployments
=> ONECOND-879 Review Nomad Deploy file - update "update stanza"

docker/ui/Dockerfile
Netflix commit https://github.com/Netflix/conductor/commit/93f67a77f947941d0f3196d4f05719491508bffb
=> Pin the Nodejs version to 9. Gulp and perhaps other dependencies.

es6rest-persistence/src/main/java/com/netflix/conductor/dao/es6rest/Elasticsearch6RestModule.java
Increase the retry timeout value to try and help resolve issues in `owf-int`.
=> Call setMaxRetryTimeoutMillis()

deploy.tmpl.nomad
/v1/health instead of `/health`
=> /v1/health instead of `/health`

es6rest-persistence/src/main/java/com/netflix/conductor/dao/es6rest/Elasticsearch6RestModule.java
Try a suggested configuration change to reduce or eliminate timeout errors. See https://jira.d3nw.com/browse/ONECOND-1102 for details. 
I think the configuration change was recommended by Damon and is something they either used for OSS or Sherlock.
=> Try Suggested ES Client Configuration (ONECOND-1102)

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
Made workflow execution (in start workflow phase) asynchronous as it impacts the sub-workflows
=> ONECOND-1130 Rerun workflow started twice. to master

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
…n startWorkflow phase) asynchronous as it impacts the sub-workflows
=> ONECOND-1130 Rerun workflow started twice. to 0.8.0-master

core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
=> Revert "ONECOND-1141 join (task) execute before previous wf finished."

.gitignore, terraform/rds/Makefile, terraform/rds/README.md, terraform/rds/aurora.tf, terraform/rds/outputs.tf, terraform/rds/provider.tf, terraform/rds/variables.tf
~draft pull request for second pass~
=> Onesupport 821

core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
=> ONECOND-1250 Transcode Workflows Failing with No VFS Filepath

conductor.hcl
Partially revert PR https://github.com/d3sw/conductor/pull/688/files
=> Partially revert "conductor dynamic creds s3 bucket access ONESUPPORT997

conductor-archiver.hcl, conductor.hcl
Based on Datadog metrics for the last month [DD metrics ](https://app.datadoghq.com/dashboard/nqu-sgd-aek/platform-efficiency-board?from_ts=1580563722948&live=true&to_ts=1583155722948&tpl_var_env=live&tpl_var_service=conductor)
=> ONEPLATENG-2319: decrease overpovisioned resources

jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java, ui/src/actions/WorkflowActions.js, ui/src/api/wfe.js, ui/src/components/workflow/executions/WorkflowList.js
=> Revert "ONECOND-911-Conductor - export report"

common/src/main/java/com/netflix/conductor/common/run/CommonParams.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java
…e SH receives WFID from Execute WF calls
=> ONECOND-1496 Conductor AsyncStart, WorkflowId in API (WF Update messages before SH receives WFID from Execute WF calls)

common/src/main/java/com/netflix/conductor/common/run/Workflow.java, conductor.hcl, core/src/main/java/com/netflix/conductor/core/execution/batch/BatchSweeper.java, core/src/main/java/com/netflix/conductor/core/execution/batch/SherlockBatchProcessor.java, postgresql-persistence/src/main/java/com/netflix/conductor/aurora/AuroraQueueDAO.java
Reverts d3sw/conductor#723
these changes are part of Sherlock v1.20, we will need to co-ordinate before merge and deploy
=> Revert "ONECOND-1544-Improve Conductor Batching for Sherlock calls"

common/src/main/java/com/netflix/conductor/common/run/Workflow.java, conductor.hcl, core/src/main/java/com/netflix/conductor/core/execution/batch/BatchSweeper.java, core/src/main/java/com/netflix/conductor/core/execution/batch/SherlockBatchProcessor.java, correlation/src/main/java/com/netflix/conductor/contribs/correlation/Context.java, correlation/src/main/java/com/netflix/conductor/contribs/correlation/Correlator.java, postgresql-persistence/src/main/java/com/netflix/conductor/aurora/AuroraQueueDAO.java
=> ONECOND-1544-Improve Conductor Batching for Sherlock calls

contribs/src/main/java/com/netflix/conductor/contribs/StatusEventPublisher.java, core/src/test/java/com/netflix/conductor/core/events/TestScriptEval.java
https://jira.d3nw.com/browse/ONECOND-1619
- added end eventMessage with a condition to only send the message on a TERMINATE status.
=> ONECOND-1619 Terminate messages for deluxe.conductor.deluxeone.streampackager.workflow.update 

common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java, core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
=> Revert "Onecond 1661"

postgresql-persistence/src/main/resources/initial_schema.sql
=> Revert "ONECOND-1770 Service Perf Analysis : DD and Splunk Dashboards and Relevant Data"

core/src/main/java/com/netflix/conductor/core/events/EventProcessor.java, core/src/main/java/com/netflix/conductor/core/events/ScriptEvaluator.java
=> Revert "ONECOND-1831-Validate handler conditions during bootstrap"

contribs/build.gradle, core/build.gradle, docker/server/Dockerfile
=> Revert "ONECOND-1957 Upgrade dd-agent library"

conductor.hcl
=> Revert "ONECOND-1976 - Nomad Job Update : Implement Spread"

conductor.hcl
=> Revert "Revert "ONECOND-1976 - Nomad Job Update : Implement Spread""

common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java, common/src/main/java/com/netflix/conductor/common/run/Workflow.java, common/src/main/java/com/netflix/conductor/common/run/WorkflowSummary.java, core/src/main/java/com/netflix/conductor/core/config/CoreModule.java, core/src/main/java/com/netflix/conductor/core/execution/ParametersUtils.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, core/src/main/java/com/netflix/conductor/core/execution/tasks/SetVariable.java, core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
=> ONECOND-2070 Implement new system task "Set Variable"

conductor.hcl, postgresql-persistence/src/main/java/com/netflix/conductor/aurora/AuroraDataSourceProvider.java, postgresql-persistence/src/main/java/com/netflix/conductor/aurora/log4j/DeluxeAuroraAppender.java, server/src/main/java/com/netflix/conductor/log4j/KeyValueLayout.java, server/src/main/java/com/netflix/conductor/server/ConductorServer.java
=> Revert "Onecond 2119 - Split Conductor to have a API and Worker component"

postgresql-persistence/src/main/resources/db/migrations/V6_1__priority_config_table_insert_values.sql
=> ONECOND-2210: Add priority configuration for ccextract, checksum and one-cdn

contribs/build.gradle, core/build.gradle
=> Release v2.49.0

core/src/main/java/com/netflix/conductor/core/execution/WorkflowSweeper.java
=> Release v2.54.0

core/src/main/java/com/netflix/conductor/dao/MetadataDAO.java, es6rest-persistence/src/main/java/com/netflix/conductor/dao/es6rest/dao/Elasticsearch6RestMetadataDAO.java, jersey/src/main/java/com/netflix/conductor/server/resources/InfoResource.java, postgresql-persistence/src/main/java/com/netflix/conductor/aurora/AuroraMetadataDAO.java, postgresql-persistence/src/main/resources/db/migrations/V8_1__add_deep_archive_restore.sql, ui/src/actions/AuthActions.js, ui/src/api/sys.js, ui/src/components/App.js, ui/src/components/common/Footer.js, ui/src/core/AuthHelper.js, ui/src/reducers/global.js
=> Release v2.58.0
